### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by fabiojansenbr** [chrispoulter/halcyon-express-api#1]
Hi Chris.

At first, im a great fan of your codes. I learn so much with. Please continue to post...

Im trying to use the forgot password feature of the api, but im having problems to make work.

Im sending a put to the specified url with this fields:

{
  "emailAddress": "email@email.com",
  "homeUrl": "https://halcyon-express-api.chrispoulter.com/",
  "passwordResetUrl": "https://halcyon-express-api.chrispoulter.com/api/account/forgotpassword"
}

In postman im receiving 504 error. this passwordResetUrl is correct? Which url should i use?

Thanks again.

**Comment by chrispoulter** [comment]
Hi Fabio,

The example hosted environment uses a Mailgun Free Account to send out password reminders.

It will only allow emails to be sent to email addresses verified by the account i.e. just mine.

This was all that was needed for my testing purposes.

When hosting the solution yourself you can select which ever email provider you want.

Thanks,
Chris
